apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: archplat
type: Opaque
stringData:
  POSTGRES_USER: app
  POSTGRES_PASSWORD: app
  POSTGRES_DB: app
  JWT_SECRET: dev-local-secret
