apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: archplat
spec:
  selector: { app: frontend }
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: archplat
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata: { labels: { app: frontend } }
    spec:
      containers:
      - name: frontend
        image: platform-frontend:dev
        imagePullPolicy: IfNotPresent
        ports: [ { containerPort: 3000 } ]
        env:
        - name: NEXT_PUBLIC_API
          valueFrom: { configMapKeyRef: { name: app-config, key: NEXT_PUBLIC_API } }
        readinessProbe:
          httpGet: { path: /, port: 3000 }
          initialDelaySeconds: 10
          periodSeconds: 10
